"""Generate the licence audit for legal review.

Constraint C5: the client is a commercial operation, so every shipped asset must
be commercially licensed. This queries the Hub live rather than trusting the
registry, because a model card can change and because "the licence I remember"
is not evidence.

Datasets are listed separately and marked by *role*. The client authorised
fitting on research-licensed corpora pending legal review, so the distinction
that matters is not the licence alone but whether an asset influences a shipped
parameter.

Run:  PYTHONPATH=. .venv/Scripts/python.exe scripts/licence_audit.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from voxscore.config import MODELS, REPORTS_DIR

# role: "shipped" influences production output; "evaluation" never does.
DATASETS = [
    ("google/fleurs", "evaluation",
     "Non-English speech for foreign-language dose-response testing"),
    ("Bhargav0044/svarah1", "evaluation",
     "Indian-accented English negatives for the fairness audit. UNGATED MIRROR of "
     "ai4bharat/Svarah - provenance must be confirmed and the official terms "
     "accepted before external citation"),
    ("hf-internal-testing/librispeech_asr_dummy", "evaluation",
     "Smoke-test audio only"),
]

REJECTED = [
    ("vennify/t5-base-grammar-correction", "cc-by-nc-sa-4.0",
     "Most-used GEC model on the Hub (86k downloads). Non-commercial."),
    ("grammarly/coedit-large", "cc-by-nc-4.0",
     "Strong instruction-tuned corrector. Non-commercial."),
    ("pszemraj/flan-t5-large-grammar-synthesis", "cc-by-nc-sa-4.0 + apache-2.0",
     "Dual-licensed with an NC term; ambiguous, so avoided."),
    ("prithivida/grammar_error_correcter_v1", "UNSTATED",
     "No licence declared. Absence of a licence is absence of a grant."),
]

PERMISSIVE = {"mit", "apache-2.0", "bsd", "bsd-2-clause", "bsd-3-clause",
              "cc0-1.0", "cc-by-4.0", "openrail", "unlicense"}


def _fetch(kind: str, repo_id: str) -> tuple[str, str]:
    from huggingface_hub import HfApi

    api = HfApi()
    try:
        info = api.model_info(repo_id) if kind == "model" else api.dataset_info(repo_id)
        lic = (info.card_data.get("license") if info.card_data else None) or "UNSTATED"
        if isinstance(lic, list):
            lic = ", ".join(lic)
        gated = str(getattr(info, "gated", False))
        return str(lic), gated
    except Exception as exc:
        return f"LOOKUP FAILED ({type(exc).__name__})", "?"


def main() -> int:
    lines: list[str] = []
    w = lines.append

    w("# Licence Audit\n")
    w("Generated by `scripts/licence_audit.py`, querying the Hugging Face Hub live.\n")
    w("**This is engineering diligence, not legal advice.** Every row needs sign-off.\n")
    w("The distinction that matters is *role*: an asset marked **shipped** influences "
      "production output, an asset marked **evaluation** never does and appears only "
      "in measurement.\n")

    w("\n## Models (all shipped)\n")
    w("| Purpose | Model | Licence (live) | Commercial | Notes |")
    w("|---|---|---|---|---|")
    problems: list[str] = []
    for key, spec in MODELS.items():
        lic, _ = _fetch("model", spec.hf_id)
        ok = any(p in lic.lower() for p in PERMISSIVE)
        if not ok:
            problems.append(f"{spec.hf_id} -> {lic}")
        mark = "yes" if ok else "**REVIEW**"
        note = spec.notes.replace("\n", " ")[:210] if spec.notes else spec.purpose
        w(f"| {key} | `{spec.hf_id}` | {lic} | {mark} | {note} |")

    w("\n## Datasets\n")
    w("| Dataset | Role | Licence (live) | Gated | Purpose |")
    w("|---|---|---|---|---|")
    for did, role, purpose in DATASETS:
        lic, gated = _fetch("dataset", did)
        w(f"| `{did}` | {role} | {lic} | {gated} | {purpose} |")

    w("\n## Rejected on licence grounds\n")
    w("Recorded so the constraint's cost is visible rather than invisible.\n")
    w("| Model | Licence | Why rejected |")
    w("|---|---|---|")
    for mid, lic, why in REJECTED:
        w(f"| `{mid}` | {lic} | {why} |")

    w("\n## What the constraint cost us\n")
    w("**Every competitive grammatical-error-correction model on the Hub is "
      "non-commercial.** The most widely used one has 86,000 downloads and is "
      "CC-BY-NC-SA; the strongest is Grammarly's, also non-commercial; the one with "
      "the most downloads of the remaining candidates declares no licence at all.\n")
    w("The only permissively licensed option is `Unbabel/gec-t5_small`, which is a "
      "t5-small. Spot-checking confirms it handles the L2 error types that matter "
      "(tense, preposition, subject-verb agreement) and leaves correct sentences "
      "untouched, so the choice is defensible -- but grammar is the one category "
      "where the licence constraint, not the method, sets the ceiling.\n")
    w("If legal will clear a non-commercial model for internal benchmarking only, "
      "quantifying that gap would be worthwhile before accepting it.\n")

    w("\n## Open items\n")
    w("1. **Svarah access.** The canonical `ai4bharat/Svarah` is gated. The fairness "
      "audit currently uses an ungated mirror with no declared licence. Accepting "
      "the official terms would let us cite the canonical source.\n")
    w("2. **Research-corpus fitting.** The client authorised fitting on "
      "research-licensed corpora pending legal review. Nothing currently does, so "
      "this remains available rather than exercised.\n")
    if problems:
        w("3. **Models needing review:**\n")
        for p in problems:
            w(f"   - {p}")

    out = REPORTS_DIR / "LICENCE_AUDIT.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    print(f"\n\nwrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
